version: "3.8"
services:
  hivision_id_photos_uniapp1:
    hostname: hivision_id_photos_uniapp1
    container_name: hivision_id_photos_uniapp1
    image: registry.cn-hangzhou.aliyuncs.com/jia_common/hivision_id_photos_uniapp:1.0.0
#    environment:
#      deploy_info: prod
    volumes:
      - ../logs/logs1:/var/log
      - /HivisionIDPhotos-Uniapp/nginx-prod.conf:/etc/nginx/nginx.conf
      - /HivisionIDPhotos-Uniapp/var/log/nginx:/var/log/nginx
      - /HivisionIDPhotos-Uniapp/conf.d:/etc/nginx/conf.d
	  - /HivisionIDPhotos-Uniapp/cert:/etc/nginx/cert
#      - /opt/upFiles:/opt/upFiles
    ports:
	  - "80:80"
      - "443:443"
      - "9191:9191"
    restart: always